### ISSUE TITLE
Unhandled error condition in craft cycle

### ISSUE THREAD

**Issue by Bjonnfesk** [Koulis2000/OCScripts#13]
cf. https://github.com/Koulis2000/MCScripts/issues/10

Due to the no match condition being unhandled, `craftCycle()` must return. This means that items that are _after_ the item for which there was no match, will not be processed.

https://github.com/Koulis2000/MCScripts/blob/922ebb0bc358e513cec3a0154ca0b357a3f3a8a8/CCTweaked/janus-dossier.lua#L219-L229

**Comment by Koulis2000** [comment]
Oversight of mine, I will investigate for other cases of returns with not releaseFileLock()

**Comment by Bjonnfesk** [comment]
Sure, but I fixed that already, that was issue #10. This issue is about the loop being forced to abort if it hits an item that doesn't match, so subsequent items in the list don't even get checked.

**Comment by Koulis2000** [comment]
If you fixed it, why is 13 open? Github is confusing.

**Comment by Bjonnfesk** [comment]
I fixed #10, which was a related issue. I haven't fixed this one.

**Comment by Koulis2000** [comment]
Oh, different issue, I see. Okay got it.

**Comment by Koulis2000** [comment]
This will now be handled by the add command. It will fill the information temporarily while waiting for the next cycle of updateRequiredItems()

https://github.com/Koulis2000/MCScripts/blob/c830e9cf6bc1b3504c4312dab0953c498881e71a/CCTweaked/janus/commands.lua#L141-L151
