### ISSUE TITLE
Duplicate code for pausing, unpausing, removing items

### ISSUE THREAD

**Issue by Bjonnfesk** [Koulis2000/OCScripts#15]
Dossier uses its own code for pausing, unpausing and removing items:

https://github.com/Koulis2000/MCScripts/blob/2cab7ac9e6ae84828c9103f0acb3eb29f155f8ba/CCTweaked/janus-dossier.lua#L84-L127

This is duplicate code, as the capability to do that already exists in `janus/commands.lua`. Dossier should call these existing methods instead.

**Comment by Koulis2000** [comment]
The commands.lua file actually uses these functions to pause/unpause/remove items when provided only with a name. Maybe I should move them in that file.

**Comment by Bjonnfesk** [comment]
Then this issue is even deeper. That means at least some of those functions in `commands.lua` are loading and saving the requested items file twice per operation.

**Comment by Koulis2000** [comment]
I have reworked the whole file. Will push the changes after I do some testing.

**Comment by Koulis2000** [comment]
Moved all the related functions to commands.lua and reduced janus.load() and janus.save() calls significantly.
