### ISSUE TITLE
Janus the Two-Faced Autocrafter doesn't autocraft

### ISSUE THREAD

**Issue by Bjonnfesk** [Koulis2000/OCScripts#7]
This is causing him an existential crisis. He doesn't feel like himselves anymore.

**Comment by Koulis2000** [comment]
Will work on it, at some point.

**Comment by Bjonnfesk** [comment]
Closed by https://github.com/Koulis2000/MCScripts/commit/37cceee192f243bcf2cd2ac85ec6cfc58689d913.
